### PR TITLE
[Feature] Add support for cGAN (MODEL)

### PR DESCRIPTION
**Pull request by nbei**

### CODE REVIEW

**Review by LeoXing1996 — APPROVED** [review]
1. Doc for `loss_scalar` is missing, and the same for `static_unconditional_gan.py`.
2. Maybe we can directly add `label` support in `sample_from_noise` of `base_gan.py` in the future?

**Review by LeoXing1996 — APPROVED** [review]

**Comment by nbei** [comment]
> 1. Doc for `loss_scalar` is missing, and the same for `static_unconditional_gan.py`.
> 2. Maybe we can directly add `label` support in `sample_from_noise` of `base_gan.py` in the future?
Sure, we will consider merging some functions into `BaseGAN` when conditional GAN is stable.

**Review by plyfager — APPROVED** [review]

**Comment by plyfager** [comment]
There are several `scalar` is written as `scaler`.

**Comment by nbei** [comment]
> There are several `scalar` is written as `scaler`.

After checking the notation in PyTorch, it should be `scaler`. I will change the several `scalar` to `scaler`.

**Pull request merged**
